spring:
  profiles:
    active:
      test

---
spring:
  config:
    activate:
      on-profile:
        - test
server:
  port: 4000
welcomeMsg: Hello from test

---
spring:
  config:
    activate:
      on-profile:
        - prod
server:
  port: 5000
welcomeMsg: Hello from prod
